apiVersion: apps/v1 
kind: Pod
metadata: 
  name: nodeapp
  labels:
    app: nodeapp
spec:
  containers:
  - name: nodeapp
  image: mikehj24/miko_flask_app:tagVersion
  ports:
    - containerPort: 8080
