apiVersion: apps/v1
kind: Deployment
metadata:
  name: miko_flask-deployment
  labels:
    app: flaskapp
spec:
  selector:
    matchLabels:
      app: flaskapp
  replicas: 3
  template:
    metadata:
      labels:
        app: flaskapp
    spec:
      containers:
      - name: mikoflaskapp
        image: mikehj24/miko_flask_app:latest
        ports:
        - containerPort: 8090
---
apiVersion: v1
kind: Service
metadata:
  name: miko_flask_app-service
spec:
  type: NodePort
  selector:
    app: flaskapp
  ports:
  - protocol: TCP
    port: 8090
    targetPort: 8090
